### ISSUE TITLE
Web Service?

### ISSUE THREAD

**Issue by arderyp** [oduwsdl/archivenow#11]
This is an amazing tool, thank you for building and publishing it!  Do you by chance know if anyone is hosting a web service that utilizes this tool to allow users to paste a url once and generate archives across all of the supported archive service providers in one go?  That would be amazing.  If now, I may be able interested in building such a tool.  Let me know what you think.

**Comment by machawk1** [comment]
@arderyp A web service that uses this module would be great, however, I would be concerned about archives blocking many requests from a single source.

**Comment by arderyp** [comment]
Good point.  If I look into it, I'll be sure to let you know. Feel free to close this issue.
