### ISSUE TITLE
documentation incorrect on how to pass parameters to a handler

### ISSUE THREAD

**Issue by npdoty** [oduwsdl/archivenow#12]
Current readme suggests this code for use in Python:
`archivenow.push("www.foxnews.com","cc","cc_api_key=$YOUR-Perma-cc-API-KEY")`
But actually, when `push()` is called directly, it seems to expect additional parameters in object form, e.g.:
`archivenow.push("www.foxnews.com","cc",{"cc_api_key":"$YOUR-Perma-cc-API-KEY"})`

**Comment by maturban** [comment]
Thanks for pointing to this. I have updated/fixed the documentation:

`archivenow.push("www.foxnews.com","all",{"cc_api_key":"8c37891..."})`

`['https://perma.cc/BD6D-2JWA', 'https://web.archive.org/web/20170809023423/http://www.foxnews.com', 'http://archive.is/0p5Qp', 'http://www.webcitation.org/6sZspjQvK']`
