### ISSUE TITLE
perma.cc handler fails with 415 Unsupported Media Type

### ISSUE THREAD

**Issue by npdoty** [oduwsdl/archivenow#13]
All use of the perma.cc handler via Python fails with errors of the following form:
> ['Error (The Perma.cc Archive): 415 Client Error: Unsupported Media Type for url: https://api.perma.cc/v1/archives/?api_key=asdfasdfasdfadf']

It looks like Perma.cc requires explicitly setting `Content-Type` to `application/json`, as per: https://perma.cc/docs/developer#create-an-archive

**Comment by maturban** [comment]
It used to work before without explicitly setting the `Content-Type`. I added it and the perma.cc handler should work now. Thanks.
