### ISSUE TITLE
Better defaults in the UI

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/archivenow#16]
For better user experience you might want to:

* [x] make the first three checkboxes checked by default
* [x] add a link to the page where Perma.cc API key can be generated, and
* [x] make the API key persist in user's browser's localstorage (if entered)

**Comment by ibnesayeed** [comment]
It looks like you have already fixed the first two after my email last night, so I checked them off.

**Comment by ibnesayeed** [comment]
Use https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage for the reference.

**Comment by maturban** [comment]
Yes, I already considered all of the three points you mentioned. Thanks.
