### ISSUE TITLE
archive.is responds with 409

### ISSUE THREAD

**Issue by maturban** [oduwsdl/archivenow#19]
Archive.is responds with 409 to requests issued through heroku (i.e. top cloud computing
providers).

**Comment by maturban** [comment]
@palewire

Archive.is now works in archivenow on heroku. The issue is that Archive.is is no longer on Cloudflare, and it seems that Cloudflare DNS propagation is slow. 

I overcome the issue by forcing resolve of archive.is to 178.62.195.5 (or 151.236.217.7) when archivenow runs on heroku. 

Here is the link to archivenow running on heroku (for testing):
https://archivenow.herokuapp.com

**Comment by palewire** [comment]
Very cool! I'll give it a try.
